name: Publish

on:
  push:
    branches: ["main", "master"]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: "Publish app somewhere"
        run: |
          echo "There will be a command to publish the app"
