name: Test

on:
  push:
    branches-ignore: ["main", "master"]

  # on pull request create
  pull_request:
    branches: ["main", "master"]

  workflow_call:

concurrency:
  group: test-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Run tests"
        run: |
          echo "there are tests. beep boop."
