name: Test

on:
  # push:
  #   branches-ignore: ["main", "master"]
  
  # # on commits in branches used in pull requests
  # pull_request_target:
  #   types:
  #     - synchronize

  # on pull request create
  pull_request:
    branches: ["main", "master"]

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Run tests"
        run: |
          echo "there are tests. beep boop."
